### ISSUE TITLE
`no such file or directory, scandir '/Users/runner/.mint/packages'` error with `MINT_PATH` and `MINT_LINK_PATH`

### ISSUE THREAD

**Issue by acevif** [irgaly/setup-mint#3]
Hi,

I encountered an error that says:
`Error: ENOENT: no such file or directory, scandir '/Users/runner/.mint/packages'`

The error was fixed after removing the `MINT_PATH` and the `MINT_LINK_PATH` environment variable specification from my GitHub actions YAML file.

Is this a bug? or a spec?
The error was fixed so far in my case, but I would like to let you know.

Thanks.

🆖:
```
env:
  DEVELOPER_DIR: /Applications/Xcode_14.0.1.app/Contents/Developer
  MINT_PATH: mint/lib
  MINT_LINK_PATH: mint/bin
```

🆗:
```
env:
  DEVELOPER_DIR: /Applications/Xcode_14.0.1.app/Contents/Developer
```
